name: ckpods_flutter
description: A comprehensive podcast app built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.2
  
  # HTTP requests
  http: ^1.1.0
  dio: ^5.4.0
  
  # Audio playback
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # Caching and Storage
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  
  # UI Components
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  
  # Notifications
  flutter_local_notifications: ^16.3.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.2
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
